### ISSUE TITLE
knitr + tikz  permission issues?

### ISSUE THREAD

**Issue by sgiannerini** [yihui/tikzDevice#106]
Dear all,

my working knitr + tikz config (since some years) is now broken probably due to some
permission problem that showed up after an upgrade (R + Miktex).
A student of mine has the same issue on her laptop (similar config).
I am on Windows 8.1 Pro 64 bit, here is a reproducible example,
the file knitr_report.Rnw  is as follows:

** begin file knitr_report.Rnw

    \documentclass[11pt]{article}
    \begin{document}

    <<c1,include=FALSE>>=
    opts_chunk$set(dev='tikz')
    @
    <<c2>>=
    hist(rnorm(100))
    @
    \end{document}
** end   file knitr_report.Rnw

then from R

    R version 3.1.3 Patched (2015-03-09 r67973) -- "Smooth Sidewalk"
    Copyright (C) 2015 The R Foundation for Statistical Computing
    Platform: i386-w64-mingw32/i386 (32-bit)

    R is free software and comes with ABSOLUTELY NO WARRANTY.
    You are welcome to redistribute it under certain conditions.
    Type 'license()' or 'licence()' for distribution details.

    R is a collaborative project with many contributors.
    Type 'contributors()' for more information and
    'citation()' on how to cite R or R packages in publications.

    Type 'demo()' for some demos, 'help()' for on-line help, or
    'help.start()' for an HTML browser interface to help.
    Type 'q()' to quit R.

    > library(knitr)
    > knit("knitr_report.Rnw")

    processing file: knitr_report.Rnw

      |
      |                                                                 |   0%
      |
      |................                                                 |  25%
      ordinary text without R code

      |
      |................................                                 |  50%
    label: c1 (with options)
    List of 1
     $ include: logi FALSE

      |
      |.................................................                |  75%
    label: c2
    Using TikZ metrics dictionary at:
            knitr_report-tikzDictionary
    Quitting from lines 9-10 (knitr_report.Rnw)
    Error in file(texLog, "r") : cannot open the connection
    In addition: Warning message:
    In file(texLog, "r") :
      cannot open file 'C:/Users/GIANNE~1/AppData/Local/Temp/Rtmpy8e4nf/tikzStringWidthCalc.log': No such file or directory

if I try again immediately without restarting I get

    > knit("knitr_report.Rnw")

    processing file: knitr_report.Rnw

      |
      |                                                                 |   0%
      |
      |................                                                 |  25%
      ordinary text without R code

      |
      |................................                                 |  50%
    label: c1 (with options)
    List of 1
     $ include: logi FALSE

      |
      |.................................................                |  75%
    label: c2
    Quitting from lines 9-10 (knitr_report.Rnw)
    Error: failed to compile figure/c2-1.tikz to PDF
    In addition: Warning message:
    running command '"C:\PROGRA~2\MIKTEX~1.9\miktex\bin\pdflatex.exe" "c2-1.tikz"' had status 1

    > sessionInfo()
    R version 3.1.3 Patched (2015-03-09 r67973)
    Platform: i386-w64-mingw32/i386 (32-bit)
    Running under: Windows 8 x64 (build 9200)

    locale:
    [1] LC_COLLATE=Italian_Italy.1252  LC_CTYPE=Italian_Italy.1252    LC_MONETARY=Italian_Italy.1252 LC_NUMERIC=C                   LC_TIME=Italian_Italy.1252

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base

    other attached packages:
    [1] tikzDevice_0.8.1 knitr_1.9

    loaded via a namespace (and not attached):
    [1] evaluate_0.5.5 filehash_2.2-2 formatR_1.0    grid_3.1.3     highr_0.4      stringr_0.6.2  tools_3.1.3

So it seems that the second time the call manages to create the file c2-1.tikz but fails to compile.
If I try to compile manually ...

    E:\Rpack\Reports\knitr\figure>pdflatex c2-1.tikz pdflatex:
    Permission denied: .\c2-1.tikz pdflatex: Data: .\c2-1.tikz

The file is locked by R, hence, I quit R and retry then I get

    E:\Rpack\Reports\knitr\figure>pdflatex c2-1.tikz
    This is pdfTeX, Version 3.14159265-2.6-1.40.15 (MiKTeX 2.9)
    entering extended mode
    (c2-1.tikz
    LaTeX2e <2014/05/01>
    Babel <3.9l> and hyphenation patterns for 68 languages loaded.
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\base\article.cls"
    Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\base\size11.clo"))
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\pgf\frontendlayer\tikz.sty"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\pgf\basiclayer\pgf.sty"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\pgf\utilities\pgfrcs.sty"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\utilities\pgfutil-common.te
    x"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\utilities\pgfutil-common-li
    sts.tex"))
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\utilities\pgfutil-latex.def
    " ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\ms\everyshi.sty"))
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\utilities\pgfrcs.code.tex")
    ) ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\pgf\basiclayer\pgfcore.sty"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\graphics\graphicx.sty"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\graphics\keyval.sty")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\graphics\graphics.sty"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\graphics\trig.sty")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\00miktex\graphics.cfg")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\pdftex-def\pdftex.def"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\oberdiek\infwarerr.sty")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\oberdiek\ltxcmds.sty"))))
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\pgf\systemlayer\pgfsys.sty"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\systemlayer\pgfsys.code.tex
    " ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\utilities\pgfkeys.code.te
    x"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\utilities\pgfkeysfiltered.c
    ode.tex"))
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\systemlayer\pgf.cfg")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\systemlayer\pgfsys-pdftex.d
    ef"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\systemlayer\pgfsys-common-p
    df.def")))
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\systemlayer\pgfsyssoftpath.
    code.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\systemlayer\pgfsysprotocol.
    code.tex")) ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\xcolor\xcolor.sty"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\00miktex\color.cfg"))
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\basiclayer\pgfcore.code.tex
    " ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\math\pgfmath.code.tex"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\math\pgfmathcalc.code.tex"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\math\pgfmathutil.code.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\math\pgfmathparser.code.tex
    ")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\math\pgfmathfunctions.code.
    tex"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\math\pgfmathfunctions.basic
    .code.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\math\pgfmathfunctions.trigo
    nometric.code.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\math\pgfmathfunctions.rando
    m.code.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\math\pgfmathfunctions.compa
    rison.code.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\math\pgfmathfunctions.base.
    code.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\math\pgfmathfunctions.round
    .code.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\math\pgfmathfunctions.misc.
    code.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\math\pgfmathfunctions.integ
    erarithmetics.code.tex")))
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\math\pgfmathfloat.code.tex"
    ))
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\basiclayer\pgfcorepoints.co
    de.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\basiclayer\pgfcorepathconst
    ruct.code.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\basiclayer\pgfcorepathusage
    .code.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\basiclayer\pgfcorescopes.co
    de.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\basiclayer\pgfcoregraphicst
    ate.code.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\basiclayer\pgfcoretransform
    ations.code.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\basiclayer\pgfcorequick.cod
    e.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\basiclayer\pgfcoreobjects.c
    ode.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\basiclayer\pgfcorepathproce
    ssing.code.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\basiclayer\pgfcorearrows.co
    de.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\basiclayer\pgfcoreshade.cod
    e.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\basiclayer\pgfcoreimage.cod
    e.tex"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\basiclayer\pgfcoreexternal.
    code.tex"))
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\basiclayer\pgfcorelayers.co
    de.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\basiclayer\pgfcoretranspare
    ncy.code.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\basiclayer\pgfcorepatterns.
    code.tex")))
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\modules\pgfmoduleshapes.cod
    e.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\modules\pgfmoduleplot.code.
    tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\pgf\compatibility\pgfcomp-version
    -0-65.sty")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\pgf\compatibility\pgfcomp-version
    -1-18.sty"))
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\pgf\utilities\pgffor.sty"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\pgf\utilities\pgfkeys.sty"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\utilities\pgfkeys.code.tex"
    )) ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\pgf\math\pgfmath.sty"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\math\pgfmath.code.tex"))
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\utilities\pgffor.code.tex"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\math\pgfmath.code.tex")))
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\frontendlayer\tikz\tikz.cod
    e.tex"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\libraries\pgflibraryplothan
    dlers.code.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\modules\pgfmodulematrix.cod
    e.tex")
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\generic\pgf\frontendlayer\tikz\librarie
    s\tikzlibrarytopaths.code.tex")))
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\preview\preview.sty"
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\latex\preview\prtightpage.def"))
    No file c2-1.aux.
    ABD: EveryShipout initializing macros
    ("C:\Program Files (x86)\MiKTeX 2.9\tex\context\base\supp-pdf.mkii"
    [Loading MPS to PDF converter (version 2006.09.02).]
    )
    Preview: Fontsize 10.95pt
    Preview: PDFoutput 1
    (c2-1.aux) )
    No pages of output.
    Transcript written on c2-1.log.

which produces a bogus pdf file (0 kb) but ..
now if I open R and retry the knit command succeeds

    > library(knitr)
    > knit("knitr_report.Rnw")

    processing file: knitr_report.Rnw

      |
      |                                                                 |   0%
      |
      |................                                                 |  25%
      ordinary text without R code

      |
      |................................                                 |  50%
    label: c1 (with options)
    List of 1
     $ include: logi FALSE

      |
      |.................................................                |  75%
    label: c2
    Using TikZ metrics dictionary at:
            knitr_report-tikzDictionary

      |
      |.................................................................| 100%
      ordinary text without R code

    output file: knitr_report.tex

    [1] "knitr_report.tex"
    >

I do not see particular problems with spaces or strange characters in the path
so that I guess it is a permission problem but I cannot figure out whether it is a matter of Miktex (pgf),
or R (tikzDevice or knitr), or something else.
Any hints would be much appreciated, thank you.

Simone

**Comment by yihui** [comment]
Seems to be the same issue as #99.

**Comment by yihui** [comment]
Should be fixed now. Please `devtools::install_github('yihui/tikzDevice')`. Thanks!

**Comment by sgiannerini** [comment]
Dear Yihui,

many thanks for looking into the matter, I have tried the fix but it does not seem to solve the issue.
After some debugging of the function tikzDevice:::getMetricsFromLatex I came to the conclusion that 
the problem is related to the fact that pdflatex does not accept  path names that use the old DOS 8.3 format with tilde, see

http://tex.stackexchange.com/questions/183568/using-8-3-path-names-with-pdflatex

See below

    library("knitr")
    debug(tikzDevice:::getMetricsFromLatex)
    knit("knitr_report.Rnw")
    Browse[2]>
    debug: texDir <- tempdir()
    Browse[2]>
    debug: texLog <- normalizePath(file.path(texDir, "tikzStringWidthCalc.log"),
        "/", FALSE)
    Browse[2]> texDir
    [1] "C:\\Users\\GIANNE~1\\AppData\\Local\\Temp\\RtmpMXHilM"

this fails as in my previous post, but if I expand manually the path

    Browse[2]> texDir <- "C:\\Users\\giannerini\\AppData\\Local\\Temp\\RtmpMXHilM"
    [...]
    Browse[2]> c
    exiting from: getMetricsFromLatex(TeXMetrics)

      |
      |.................................................................| 100%
      ordinary text without R code


    output file: knitr_report.tex

    [1] "knitr_report.tex"

this succeeds, I think some workarounds are indicated on the link provided.
Thank you
Simone

**Comment by yihui** [comment]
@sgiannerini I just pushed another fix. Could you test it again? Thanks a lot for the investigation and identifying the underlying problem.

**Comment by sgiannerini** [comment]
@yihui thank you very much for the prompt reply, this seems to fix the issue.
ciao
Simone

**Comment by krlmlr** [comment]
@yihui Thanks a lot for taking care of this. I think this fix alone warrants a CRAN release.?

**Comment by yihui** [comment]
@krlmlr Yes, I think so.
